### ISSUE TITLE
Corrigir Warning de compilação

### ISSUE THREAD

**Issue by arthurbdiniz** [TecProg2017-2/mindscape#51]
warning: passing NULL to non-pointer argument 1 of ‘engine::KeyboardEvent::KeyboardEvent(unsigned int, engine::KeyboardEvent::State, unsigned int, bool)’ [-Wconversion-null]);

**Comment by brunapinos** [comment]
https://github.com/TecProg2017-2/mindscape/commit/6cab58389f31dcc858eac4406adfdf7a4e3d72bc
